version: '3.9'

services:
  safebox-authentication-db:
    container_name: safebox-authentication-db
    image: postgres:13.4-alpine
    restart: on-failure
    ports:
      - "54321:5432"
    volumes:
      - rv-volume-safebox-authentication:/var/lib/postgresql/data
    env_file:
      - postgres.dev.env
    networks:
      internal-net:

  safebox-holder-db:
    container_name: safebox-holder-db
    image: postgres:13.4-alpine
    ports:
      - "54320:5432"
    restart: on-failure
    volumes:
      - rv-volume-safebox-holder:/var/lib/postgresql/data
    env_file:
      - postgres.dev.env
    networks:
      internal-net:

  rabbitmq:
    container_name: Rabbit-Server
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      internal-net:

volumes:
  rv-volume-safebox-authentication:
  rv-volume-safebox-holder:
  rv-gradle-cache:

networks:
  internal-net:
    name: internal-net
